#!/bin/sh
#
# Sets environment by replacing hosts file with the one of the environment - Arbetsförmedlingen only.

# # Colors
Color_Off='\033[0m'       # Text Reset
Green='\033[0;32m'        # Green
Yellow='\033[0;33m'       # Yellow
Cyan='\033[0;36m'         # Cyan

SOURCE=~/Sites/config/bramiljovalfiler/hosts-${1}-egna_tillagg.txt
TARGET=/private/etc/hosts

echo -e "${Cyan}Replacing hosts file...${Color_Off}"
#rm $TARGET
sudo cp -f $SOURCE $TARGET
source $TARGET 2> /dev/null
echo -e "${Green}You are now running the ${Yellow}${1}${Green} hosts file${Color_Off}"