cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'caskroom/versions'
tap 'puma/puma'

brew 'ack'
brew 'zsh'
brew 'coreutils'
brew 'grc'
brew 'libgit2'
brew 'openssl'
brew 'ncdu'
# brew 'nvm' installed through lukechilds/zsh-nvm through antigen
brew 'readline'
brew 'postgresql'
brew 'spaceman-diff'
brew 'unrar'
brew 'wget'
brew 'youtube-dl'
brew 'elixir'
brew 'git-flow'
brew 'watchman'
#brew 'yarn' --without-node

cask 'visual-studio-code'
cask 'firefox'
cask 'google-chrome'
cask 'slack'
cask 'keyboardcleantool'
cask 'istat-menus'
cask 'iterm2'
cask 'sketch'
cask 'dash'
cask 'docker'
cask 'the-unarchiver'
cask 'spotify'
cask 'rocket'
cask 'jetbrains-toolbox'
cask 'spectacle'
cask 'backblaze'
cask 'toggl'
cask 'zeplin'
#cask 'little-snitch'